{% set name = "napari-molecule-reader" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-molecule-reader-{{ version }}.tar.gz
  sha256: 16f09a43246b1a3923e9ab8e036a3b22d6347b22bc425c30791aa8ece2948854

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - atomium
    - numpy
    - pandas
    - python >=3.7
    - scipy

test:
  imports:
    - napari_molecule_reader
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brisvag/napari-molecule-reader
  summary: A napari plugin that read molecular structure files.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brisvag
    - conda-forge/napari
