{% set name = "napari-molecule-reader" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 136ac17f9331fce6e0f4b32eb0d570e345a6a03ba8996f577ddea971ce8da1b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - atomium
    - numpy
    - pandas
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - napari_molecule_reader
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/brisvag/napari-molecule-reader
  summary: A napari plugin that read molecular structure files.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brisvag
    - goanpeca
    - jaimergp
